# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 7.x version
  - 7.0
  - 7.1

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

services:
  - mysql
# execute any number of scripts before the test run, custom env's are available as variables
before_script:
- mysql -e "create database IF NOT EXISTS ua1_so;"
- mysql -u root "CREATE USER 'ua1'@'localhost' IDENTIFIED BY 'Ua1password0)';"
- mysql -u root "GRANT ALL PRIVILEGES ON ua1_so TO 'ua1'@'localhost';"
- mysql -u root ua1_so < sql_export/ua1_so-1.sql

script: phpunit --configuration phpunit.xml --coverage-text